version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html/secd
permissions:
   - object: /var/www/html/secd
     pattern: "**"
     owner: ubuntu
     group: ubuntu
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/installapache.sh
      runas: root
    - location: scripts/startapache.sh
      runas: root
   AfterInstall:
    - location: scripts/restartapache.sh
      runas: root
